apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.registry.name }}": {
          "username": "{{ .Values.registry.username }}",
          "password": "{{ .Values.registry.password }}"
        }
      }
    }